version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src/

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cbUser
      POSTGRES_PASSWORD: cbViagensPass
      POSTGRES_DB: cbViagens
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
